
[colors]
  draw_bold_text_with_bright_colors = true

[window]
startup_mode = "Maximized"
decorations = "none"

  [window.dimensions]
  columns = 80
  lines = 25

[font]
size = 10
builtin_box_drawing = true

  [font.normal]
  family = "Fira Code"
  style = "Regular"

  [font.bold]
  family = "Fira Code"
  style = "Bold"

  [font.italic]
  family = "Fira Code"
  style = "Italic"

  [font.bold_italic]
  family = "Fira Code"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[selection]
save_to_clipboard = true

[cursor]
unfocused_hollow = true

  [cursor.style]
  shape = "Block"

[general]
live_config_reload = true

[terminal]

[terminal.shell]
program = "/bin/bash"
